services:
  - type: web
    name: engineering-dashboard-frontend
    env: node
    buildCommand: npm install && node node_modules/vite/bin/vite.js build
    startCommand: node node_modules/serve/build/main.js dist -p $PORT
    envVars:
      - key: VITE_API_URL
        value: https://dashbord-5u0i.onrender.com
