#!/usr/bin/env python3
"""Migrate data from the legacy SQLite dashboard.db into PostgreSQL, preserving ids.

Run against a COPY of the production database — the source is opened without any
locking guarantees, so migrating a live file that's also being written by the app
can read an inconsistent snapshot.

Usage:
    python scripts/migrate_sqlite_to_pg.py \
        --sqlite-path /path/to/dashboard.db \
        --database-url postgresql://user:pass@host/db \
        [--dry-run] [--tables team_members dev_metrics ...]

--database-url defaults to $DATABASE_URL, --sqlite-path defaults to $SQLITE_PATH.
Exits non-zero if any table's row count/checksum doesn't match after loading, or a
table failed to load (destination not empty, connection error, etc).
"""
import argparse
import hashlib
import os
import sqlite3
import sys

import psycopg2
import psycopg2.extras

# Dependency order: team_members (and roadmap_epics, which roadmap_tasks references
# via owner_id) must load before every table with an enforced FK to them. Everything
# else here has no cross-table FK constraint, but is still ordered for readability.
TABLE_ORDER = [
    "departments",
    "team_members",
    "roadmap_epics",
    "roadmap_tasks",
    "roadmap_objectives",
    "roadmap_meta",
    "score_rules",
    "config",
    "ai_usage_cache",
    "dev_metrics",
    "support_metrics",
    "docs_metrics",
    "weekly_tasks",
    "sync_log",
    "api_key_mapping",
    "ai_usage",
    "daily_reports",
    "commit_log",
    "pr_log",
    "ai_events",
    "ai_usage_daily",
    "ai_tool_sessions",
    "performance_scores",
    "tasks",
    "weekly_changes",
    "gantt_assignments",
    "gantt_visibility",
    "backlog_items",
    "backlog_retired",
]


def table_columns(sqlite_conn, table):
    return [row[1] for row in sqlite_conn.execute(f"PRAGMA table_info({table})").fetchall()]


def has_identity_id(sqlite_conn, table):
    """True if `table.id` originated from `INTEGER PRIMARY KEY AUTOINCREMENT` —
    those become `GENERATED BY DEFAULT AS IDENTITY` on the Postgres side and need
    OVERRIDING SYSTEM VALUE to accept an explicit id, plus a setval() afterwards."""
    row = sqlite_conn.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()
    if not row or not row[0]:
        return False
    return "AUTOINCREMENT" in row[0].upper() and "id" in table_columns(sqlite_conn, table)


def row_checksum(rows):
    """Order-independent checksum: XOR of a truncated SHA-256 digest per row, so
    row order (which the source and destination need not agree on) doesn't matter."""
    acc = 0
    for row in rows:
        text = "|".join("" if v is None else str(v) for v in row)
        digest = hashlib.sha256(text.encode("utf-8")).digest()
        acc ^= int.from_bytes(digest[:8], "big")
    return f"{acc:016x}"


def fetch_sqlite_table(sqlite_conn, table):
    cols = table_columns(sqlite_conn, table)
    rows = sqlite_conn.execute(f"SELECT {', '.join(cols)} FROM {table}").fetchall()
    return cols, [tuple(r) for r in rows]


def fetch_pg_rows(pg_conn, table, cols):
    with pg_conn.cursor() as cur:
        cur.execute(f"SELECT {', '.join(cols)} FROM {table}")
        return cur.fetchall()


def pg_row_count(pg_conn, table):
    with pg_conn.cursor() as cur:
        cur.execute(f"SELECT COUNT(*) FROM {table}")
        return cur.fetchone()[0]


def load_table(pg_conn, table, cols, rows, identity):
    if not rows:
        return
    col_list = ", ".join(cols)
    overriding = " OVERRIDING SYSTEM VALUE" if identity else ""
    sql = f"INSERT INTO {table} ({col_list}){overriding} VALUES %s"
    with pg_conn.cursor() as cur:
        psycopg2.extras.execute_values(cur, sql, rows, page_size=500)
        if identity:
            cur.execute(
                f"SELECT setval(pg_get_serial_sequence(%s, 'id'), "
                f"(SELECT COALESCE(MAX(id), 1) FROM {table}))",
                (table,),
            )


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--sqlite-path", default=os.environ.get("SQLITE_PATH", "./dashboard.db")
    )
    parser.add_argument("--database-url", default=os.environ.get("DATABASE_URL", ""))
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--tables", nargs="*", help="Limit migration to these tables (for testing)"
    )
    args = parser.parse_args()

    if not args.database_url:
        sys.exit("error: --database-url or DATABASE_URL is required")
    if not os.path.exists(args.sqlite_path):
        sys.exit(f"error: SQLite file not found: {args.sqlite_path}")

    tables = args.tables or TABLE_ORDER
    unknown = [t for t in tables if t not in TABLE_ORDER]
    if unknown:
        sys.exit(f"error: unknown table(s) not in TABLE_ORDER: {unknown}")

    sqlite_conn = sqlite3.connect(args.sqlite_path)

    try:
        pg_conn = psycopg2.connect(args.database_url)
    except Exception as ex:
        sys.exit(f"error: could not connect to --database-url: {ex}")

    report = []
    failed = False

    for table in tables:
        identity = has_identity_id(sqlite_conn, table)
        cols, rows = fetch_sqlite_table(sqlite_conn, table)
        src_count = len(rows)
        src_checksum = row_checksum(rows)

        if args.dry_run:
            report.append((table, src_count, "-", src_checksum, "-", "DRY-RUN"))
            continue

        existing = pg_row_count(pg_conn, table)
        if existing:
            report.append(
                (table, src_count, existing, src_checksum, "-", "SKIPPED (dest not empty)")
            )
            failed = True
            continue

        try:
            load_table(pg_conn, table, cols, rows, identity)
            pg_conn.commit()
        except Exception as ex:
            pg_conn.rollback()
            report.append((table, src_count, 0, src_checksum, "-", f"FAILED: {ex}"))
            failed = True
            continue

        dest_rows = fetch_pg_rows(pg_conn, table, cols)
        dest_count = len(dest_rows)
        dest_checksum = row_checksum(dest_rows)
        ok = dest_count == src_count and dest_checksum == src_checksum
        status = "OK" if ok else "MISMATCH"
        failed = failed or not ok
        report.append((table, src_count, dest_count, src_checksum, dest_checksum, status))

    header = f"{'table':<22}{'src':>6}{'dest':>6}  {'src_checksum':<18}{'dest_checksum':<18}status"
    print(header)
    print("-" * len(header))
    for row in report:
        print(f"{row[0]:<22}{row[1]:>6}{row[2]:>6}  {row[3]:<18}{row[4]:<18}{row[5]}")

    sqlite_conn.close()
    pg_conn.close()
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
